name: "Setup Git"

runs:
  using: "composite"
  steps:
    - name: "Setup Git"
      shell: bash
      run: |
        echo "STEP: Setup Git"
        git config --global user.name "Guilherme Caponetto"
        git config --global user.email "638737+caponetto@users.noreply.github.com"
