name: "Setup environment"
description: "Setup environment for CI/CD pipelines"

inputs:
  path:
    description: "context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Setup Git"
      shell: bash
      run: |
        echo "STEP: Setup Git"
        git config --global user.name "Guilherme Caponetto"
        git config --global user.email "638737+caponetto@users.noreply.github.com"

    - name: "Setup Node"
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: "npm"
        cache-dependency-path: ${{ inputs.path }}/package-lock.json

    - name: "Bootstrap"
      shell: bash
      run: |
        echo "STEP: Bootstrap"
        cd ${{ inputs.path }}
        npm ci
