name: "Setup environment"

inputs:
  os:
    description: "Operating System"
    required: false
    default: "ubuntu-latest"
  path:
    description: "context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Setup Git"
      shell: bash
      run: |
        echo "STEP: Setup Git"
        git config --global user.name "Guilherme Caponetto"
        git config --global user.email "638737+caponetto@users.noreply.github.com"

    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "yarn"
        cache-dependency-path: ${{ inputs.path }}/yarn.lock

    - name: "Bootstrap"
      shell: bash
      run: |
        echo "STEP: Bootstrap"
        cd ${{ inputs.path }}
        yarn install

    - name: "Check yarn.lock"
      shell: bash
      run: |
        echo "STEP: Check yarn.lock"
        cd ${{ inputs.path }}
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]

    - name: "Check format"
      shell: bash
      run: |
        echo "STEP: Check format"
        cd ${{ inputs.path }}
        yarn format:check

    - name: "Start Xvfb (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Start Xvfb (Ubuntu only)"
        cd ${{ inputs.path }}
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
            /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        fi

    - name: "Increase inotify watches (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Increase inotify watches (Ubuntu only)"
        cd ${{ inputs.path }}
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        fi
