name: "Setup environment"

runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: actions/setup-node@v1
      with:
        node-version: 16.2.0

    - name: "Setup Yarn"
      shell: bash
      run: |
        echo "STEP: Setup Yarn"
        npm install -g yarn@1.22.10
        yarn config set network-timeout 1000000

    - name: "Bootstrap"
      shell: bash
      run: |
        echo "STEP: Bootstrap"
        yarn install

    - name: "Check yarn.lock"
      shell: bash
      run: |
        echo "STEP: Check yarn.lock"
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]

    - name: "Check dependencies mismatches"
      shell: bash
      run: |
        echo "STEP: Check dependencies mismatches"
        npx --yes syncpack list-mismatches

    - name: "Check format"
      shell: bash
      run: |
        echo "STEP: Check format"
        yarn format:check
