name: "Setup environment"

inputs:
  os:
    description: "Operating System"
    required: false
    default: "ubuntu-latest"
  path:
    description: "context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Setup Git"
      shell: bash
      run: |
        echo "STEP: Setup Git"
        git config --global user.name "Guilherme Caponetto"
        git config --global user.email "638737+caponetto@users.noreply.github.com"

    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - name: "Bootstrap"
      shell: bash
      run: |
        echo "STEP: Bootstrap"
        cd ${{ inputs.path }}
        npm install

    - name: "Check package-lock.json"
      shell: bash
      run: |
        echo "STEP: Check package-lock.json"
        cd ${{ inputs.path }}
        git diff package-lock.json;
        [ "0" == "$(git diff package-lock.json | wc -l | tr -d ' ')" ]

    - name: "Check format"
      shell: bash
      run: |
        echo "STEP: Check format"
        cd ${{ inputs.path }}
        npm run format:check
