#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the issues before committing."
  exit 1
fi

npm run format:check
if [ $? -ne 0 ]; then
  echo "Code formatting check failed. Please run 'npm run format' to fix the issues."
  exit 1
fi
