name: "Publish"

on:
  workflow_dispatch:

env:
  GTM_ID: ${{ secrets.GTM_ID }}
  DISPLAY: ":99.0"
  START_SERVER_AND_TEST_INSECURE: "true"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout personal-webapp"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/personal-webapp

      - name: "Checkout caponetto.github.io"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/caponetto.github.io
          token: ${{ secrets.TOKEN }}
          repository: caponetto/caponetto.github.io

      - name: "Setup environment"
        uses: ./personal-webapp/.github/actions/setup-env
        with:
          path: personal-webapp

      - name: "Build"
        working-directory: ${{ github.workspace }}/personal-webapp
        shell: bash
        run: |
          yarn build:prod

      - name: "Test"
        working-directory: ${{ github.workspace }}/personal-webapp
        shell: bash
        run: |
          yarn test

      - name: "Deploy to GitHub Pages (caponetto.github.io)"
        working-directory: ${{ github.workspace }}/caponetto.github.io
        shell: bash
        run: |
          echo "Reset deployment dir"
          shopt -s extglob
          rm -rf -- !(".well-known"|"poc"|".nojekyll"|"LICENSE"|"README.md"|"_config.yml"|"CNAME")

          echo "Copy resources"
          cp -r ${{ github.workspace }}/personal-webapp/dist/* .

          echo "Configure git"
          git config --global user.name "Guilherme Caponetto"
          git config --global user.email "638737+caponetto@users.noreply.github.com"

          echo "Commit changes and push"
          git add .
          git commit -m "Deploy ${{ github.sha }}" || echo "No changes."
          git push origin main
