name: "Staging"

on:
  workflow_dispatch:

env:
  GTM_ID: ""
  CONTEXT_PATH: "/staging"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout personal-webapp"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/personal-webapp

      - name: "Checkout caponetto.github.io"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/caponetto.github.io
          token: ${{ secrets.TOKEN }}
          repository: caponetto/caponetto.github.io

      - name: "Setup Git"
        uses: ./personal-webapp/.github/actions/setup-git

      - name: "Setup environment"
        uses: ./personal-webapp/.github/actions/setup-env
        with:
          path: personal-webapp

      - name: "Build"
        working-directory: ${{ github.workspace }}/personal-webapp
        shell: bash
        run: |
          yarn build:prod

      - name: "Deploy to GitHub Pages Staging area (caponetto.github.io)"
        working-directory: ${{ github.workspace }}/caponetto.github.io
        shell: bash
        run: |
          echo "Reset deployment dir"
          rm -rf staging
          mkdir staging
          cd staging

          echo "Copy resources"
          cp -r ${{ github.workspace }}/personal-webapp/dist/* .

          echo "Commit changes and push"
          git add .
          git commit -m "Staging Deploy ${{ github.sha }}" || echo "No changes."
          git push origin main
